// ============================================================
// UNIQUE STAYS USA — Curated Listings Data
// Design: Wanderer's Postcard Collection
// ============================================================

export type Platform = 'Airbnb' | 'VRBO' | 'Wander' | 'Direct';
export type Category =
  | 'Treehouses'
  | 'Geodesic Domes'
  | 'Houseboats'
  | 'Lighthouses'
  | 'Converted Barns'
  | 'Cave Dwellings'
  | 'A-Frame Cabins'
  | 'Tiny Homes'
  | 'Glamping'
  | 'Castles & Estates';

export interface Stay {
  id: string;
  title: string;
  subtitle: string;
  location: string;
  state: string;
  region: 'West' | 'Southwest' | 'South' | 'Midwest' | 'Northeast' | 'Southeast';
  category: Category;
  platform: Platform;
  affiliateUrl: string;
  image: string;
  price: number;
  priceUnit: 'night';
  rating: number;
  reviewCount: number;
  sleeps: number;
  bedrooms: number;
  tags: string[];
  description: string;
  featured?: boolean;
  editorsPick?: boolean;
  isNew?: boolean;
}

export const STAYS: Stay[] = [
  {
    id: 'redwood-treehouse-ca',
    title: 'Enchanted Redwood Treehouse',
    subtitle: 'Nestled among ancient giants',
    location: 'Guerneville, California',
    state: 'California',
    region: 'West',
    category: 'Treehouses',
    platform: 'Airbnb',
    affiliateUrl: 'https://www.airbnb.com/s/treehouses--California',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/86702083/ByQr52J2uJxPcTScSSaduY/hero-treehouse-JWbjZXvAKxUiXAg4QS7BnL.webp',
    price: 285,
    priceUnit: 'night',
    rating: 4.97,
    reviewCount: 312,
    sleeps: 4,
    bedrooms: 2,
    tags: ['Hot Tub', 'Forest Views', 'Fairy Lights', 'Deck'],
    description: 'Wake up 40 feet above the forest floor in this stunning treehouse perched among century-old redwoods. String lights, a wraparound deck, and floor-to-ceiling windows make this the most magical stay in Northern California.',
    featured: true,
    editorsPick: true,
  },
  {
    id: 'desert-dome-ut',
    title: 'Stargazer Geodesic Dome',
    subtitle: 'Sleep under a billion stars',
    location: 'Moab, Utah',
    state: 'Utah',
    region: 'Southwest',
    category: 'Geodesic Domes',
    platform: 'Airbnb',
    affiliateUrl: 'https://www.airbnb.com/s/glamping--Utah',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/86702083/ByQr52J2uJxPcTScSSaduY/hero-dome-fNq53JMSCre9pYDm759BF5.webp',
    price: 340,
    priceUnit: 'night',
    rating: 4.95,
    reviewCount: 198,
    sleeps: 2,
    bedrooms: 1,
    tags: ['Stargazing', 'Fire Pit', 'Desert Views', 'Telescope'],
    description: 'A transparent geodesic dome set against Utah\'s otherworldly red rock formations. The king bed faces the sky so you can watch the Milky Way from your pillow. Includes a private fire pit and telescope.',
    featured: true,
    editorsPick: true,
  },
  {
    id: 'tugboat-houseboat-me',
    title: 'The Autumn Breeze Tugboat',
    subtitle: 'A floating New England escape',
    location: 'Sebago Lake, Maine',
    state: 'Maine',
    region: 'Northeast',
    category: 'Houseboats',
    platform: 'VRBO',
    affiliateUrl: 'https://www.vrbo.com/search/keywords:houseboat-maine',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/86702083/ByQr52J2uJxPcTScSSaduY/hero-houseboat-6e6D3bBeEjwZSSmSxByNAZ.webp',
    price: 420,
    priceUnit: 'night',
    rating: 4.93,
    reviewCount: 87,
    sleeps: 4,
    bedrooms: 2,
    tags: ['Waterfront', 'Kayaks Included', 'Autumn Foliage', 'Dock'],
    description: 'A lovingly restored 1920s tugboat transformed into a cozy floating home. Porthole windows, original hardwood, and a private dock with kayaks. Best experienced during peak fall foliage season.',
    featured: true,
    editorsPick: false,
  },
  {
    id: 'lighthouse-maine',
    title: 'Keeper\'s Watch Lighthouse',
    subtitle: 'Your own private beacon',
    location: 'Pemaquid Point, Maine',
    state: 'Maine',
    region: 'Northeast',
    category: 'Lighthouses',
    platform: 'Airbnb',
    affiliateUrl: 'https://www.airbnb.com/s/lighthouse--Maine',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/86702083/ByQr52J2uJxPcTScSSaduY/stay-lighthouse-nHqEjjahnK5Rot6MrdavF2.webp',
    price: 495,
    priceUnit: 'night',
    rating: 4.98,
    reviewCount: 64,
    sleeps: 6,
    bedrooms: 3,
    tags: ['Ocean Views', 'Rocky Coast', 'Historic', 'Spiral Staircase'],
    description: 'A fully restored 19th-century lighthouse keeper\'s dwelling on the rugged Maine coast. Climb the spiral staircase to the lantern room for 360° ocean views. Lobster boats pass by at dawn.',
    featured: false,
    editorsPick: true,
  },
  {
    id: 'barn-tennessee',
    title: 'The Golden Hour Barn',
    subtitle: 'Rustic luxury in the hills',
    location: 'Leiper\'s Fork, Tennessee',
    state: 'Tennessee',
    region: 'South',
    category: 'Converted Barns',
    platform: 'VRBO',
    affiliateUrl: 'https://www.vrbo.com/search/keywords:barn-tennessee',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/86702083/ByQr52J2uJxPcTScSSaduY/stay-barn-JvwT2jj9bCD3f5FXSDQu76.webp',
    price: 375,
    priceUnit: 'night',
    rating: 4.91,
    reviewCount: 143,
    sleeps: 8,
    bedrooms: 4,
    tags: ['Fire Pit', 'String Lights', 'Rolling Hills', 'Farm Animals'],
    description: 'An 1890s tobacco barn transformed into a stunning event-worthy retreat. Original timber beams, a wildflower meadow, and a stone fire pit with Adirondack chairs. Nashville is just 45 minutes away.',
    featured: false,
    editorsPick: false,
    isNew: false,
  },
  {
    id: 'cave-sedona-az',
    title: 'The Sandstone Sanctuary',
    subtitle: 'A cave carved by time',
    location: 'Sedona, Arizona',
    state: 'Arizona',
    region: 'Southwest',
    category: 'Cave Dwellings',
    platform: 'Airbnb',
    affiliateUrl: 'https://www.airbnb.com/s/cave--Arizona',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/86702083/ByQr52J2uJxPcTScSSaduY/stay-cave-DzUjvuyWRjdY2ijdYdCnYC.webp',
    price: 520,
    priceUnit: 'night',
    rating: 4.99,
    reviewCount: 41,
    sleeps: 2,
    bedrooms: 1,
    tags: ['Red Rocks', 'Vortex Energy', 'Round Door', 'Desert Garden'],
    description: 'Carved directly into Sedona\'s iconic red sandstone cliffs, this extraordinary cave dwelling features a round hobbit door, ancient adobe walls, and unobstructed views of Cathedral Rock. Truly one of a kind.',
    featured: false,
    editorsPick: true,
    isNew: true,
  },
  {
    id: 'aframe-colorado',
    title: 'Summit A-Frame Retreat',
    subtitle: 'High altitude, high style',
    location: 'Breckenridge, Colorado',
    state: 'Colorado',
    region: 'West',
    category: 'A-Frame Cabins',
    platform: 'Wander',
    affiliateUrl: 'https://www.wander.com',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/86702083/ByQr52J2uJxPcTScSSaduY/stay-cabin-AmUuWeL8kRptWi2GUxLZh5.webp',
    price: 450,
    priceUnit: 'night',
    rating: 4.96,
    reviewCount: 229,
    sleeps: 6,
    bedrooms: 3,
    tags: ['Hot Tub', 'Ski-In/Ski-Out', 'Mountain Views', 'Fireplace'],
    description: 'A picture-perfect A-frame cabin at 10,000 feet with ski-in/ski-out access, a steaming outdoor hot tub, and floor-to-ceiling windows framing the Rockies. The wood-burning fireplace is the stuff of dreams.',
    featured: false,
    editorsPick: false,
    isNew: true,
  },
  {
    id: 'dome-smoky-mountains-tn',
    title: 'Smoky Mountain Bubble Dome',
    subtitle: 'Where forest meets the cosmos',
    location: 'Gatlinburg, Tennessee',
    state: 'Tennessee',
    region: 'Southeast',
    category: 'Geodesic Domes',
    platform: 'Airbnb',
    affiliateUrl: 'https://www.airbnb.com/s/dome--Tennessee',
    image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800&q=80',
    price: 265,
    priceUnit: 'night',
    rating: 4.89,
    reviewCount: 176,
    sleeps: 2,
    bedrooms: 1,
    tags: ['Forest Views', 'Hot Tub', 'Stargazing', 'Secluded'],
    description: 'A transparent glamping dome nestled in the Smoky Mountains forest. Watch deer wander past your bed at dawn, then soak in the private hot tub under a canopy of fireflies at dusk.',
    featured: false,
    editorsPick: false,
  },
  {
    id: 'treehouse-oregon',
    title: 'Pacific Canopy Treehouse',
    subtitle: 'Among the Douglas firs',
    location: 'Hood River, Oregon',
    state: 'Oregon',
    region: 'West',
    category: 'Treehouses',
    platform: 'Airbnb',
    affiliateUrl: 'https://www.airbnb.com/s/treehouses--Oregon',
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
    price: 310,
    priceUnit: 'night',
    rating: 4.94,
    reviewCount: 258,
    sleeps: 3,
    bedrooms: 1,
    tags: ['Columbia River Gorge', 'Hiking', 'Waterfall Views', 'Deck'],
    description: 'Perched 35 feet up in old-growth Douglas firs with views of the Columbia River Gorge. A rope bridge connects the sleeping loft to the main deck. Multnomah Falls is a 20-minute drive.',
    featured: false,
    editorsPick: false,
    isNew: true,
  },
  {
    id: 'tiny-home-texas',
    title: 'The Lone Star Tiny House',
    subtitle: 'Big Texas sky, tiny footprint',
    location: 'Wimberley, Texas',
    state: 'Texas',
    region: 'South',
    category: 'Tiny Homes',
    platform: 'VRBO',
    affiliateUrl: 'https://www.vrbo.com/search/keywords:tiny-house-texas',
    image: 'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800&q=80',
    price: 195,
    priceUnit: 'night',
    rating: 4.88,
    reviewCount: 334,
    sleeps: 2,
    bedrooms: 1,
    tags: ['Hill Country', 'Creek Access', 'Hammock', 'Stargazing'],
    description: 'A beautifully crafted 300 sq ft tiny home on a working Hill Country ranch. Swim in the crystal-clear Blanco River, stargaze from the hammock, and wake to the sound of roosters.',
    featured: false,
    editorsPick: false,
  },
  {
    id: 'glamping-montana',
    title: 'Glacier Safari Tent',
    subtitle: 'Luxury at the edge of wilderness',
    location: 'Whitefish, Montana',
    state: 'Montana',
    region: 'West',
    category: 'Glamping',
    platform: 'Wander',
    affiliateUrl: 'https://www.wander.com',
    image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&q=80',
    price: 385,
    priceUnit: 'night',
    rating: 4.92,
    reviewCount: 112,
    sleeps: 4,
    bedrooms: 2,
    tags: ['Glacier Views', 'Wildlife', 'Wood Stove', 'Guided Hikes'],
    description: 'A luxury canvas safari tent on the edge of Glacier National Park. Grizzly bears roam the meadow at dusk. Includes a wood-burning stove, Persian rugs, and a private chef option.',
    featured: false,
    editorsPick: true,
  },
  {
    id: 'castle-hudson-valley',
    title: 'The Hudson Valley Castle',
    subtitle: 'Your kingdom awaits',
    location: 'Rhinebeck, New York',
    state: 'New York',
    region: 'Northeast',
    category: 'Castles & Estates',
    platform: 'Airbnb',
    affiliateUrl: 'https://www.airbnb.com/s/castle--New-York',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
    price: 1200,
    priceUnit: 'night',
    rating: 4.97,
    reviewCount: 53,
    sleeps: 12,
    bedrooms: 6,
    tags: ['Historic', 'Wine Cellar', 'Gardens', 'Hudson River Views'],
    description: 'A genuine 19th-century stone castle on 40 acres in the Hudson Valley. Six bedrooms, a medieval great hall, wine cellar, and formal gardens. The most dramatic backdrop for a family reunion or milestone celebration.',
    featured: false,
    editorsPick: false,
  },
];

export const CATEGORIES: { id: Category; emoji: string; label: string; count: number }[] = [
  { id: 'Treehouses', emoji: '🌲', label: 'Treehouses', count: 48 },
  { id: 'Geodesic Domes', emoji: '🔮', label: 'Geodesic Domes', count: 34 },
  { id: 'Houseboats', emoji: '⛵', label: 'Houseboats', count: 27 },
  { id: 'Lighthouses', emoji: '🏮', label: 'Lighthouses', count: 19 },
  { id: 'Converted Barns', emoji: '🏚️', label: 'Converted Barns', count: 56 },
  { id: 'Cave Dwellings', emoji: '🪨', label: 'Cave Dwellings', count: 12 },
  { id: 'A-Frame Cabins', emoji: '🏔️', label: 'A-Frame Cabins', count: 73 },
  { id: 'Tiny Homes', emoji: '🏡', label: 'Tiny Homes', count: 89 },
  { id: 'Glamping', emoji: '⛺', label: 'Glamping', count: 61 },
  { id: 'Castles & Estates', emoji: '🏰', label: 'Castles & Estates', count: 8 },
];

export const REGIONS = ['All', 'West', 'Southwest', 'South', 'Midwest', 'Northeast', 'Southeast'] as const;
export type Region = typeof REGIONS[number];
