// ============================================================
// UNIQUE STAYS USA — Curated Listings Data
// Design: Wanderer's Postcard Collection
// Hub & Spoke Model: unique | work-friendly | pet-friendly | rv-ready | ev-ready
// ============================================================

export type Platform = 'Airbnb' | 'VRBO' | 'Wander' | 'Direct';
export type Category =
  | 'Treehouses'
  | 'Geodesic Domes'
  | 'Houseboats'
  | 'Lighthouses'
  | 'Converted Barns'
  | 'Cave Dwellings'
  | 'A-Frame Cabins'
  | 'Tiny Homes'
  | 'Glamping'
  | 'Castles & Estates';

export type SpokeSlug = 'unique' | 'work-friendly' | 'pet-friendly' | 'rv-ready' | 'ev-ready';

export interface Stay {
  id: string;
  title: string;
  subtitle: string;
  location: string;
  state: string;
  region: 'West' | 'Southwest' | 'South' | 'Midwest' | 'Northeast' | 'Southeast';
  category: Category;
  platform: Platform;
  affiliateUrl: string;
  image: string;
  price: number;
  priceUnit: 'night';
  rating: number;
  reviewCount: number;
  sleeps: number;
  bedrooms: number;
  tags: string[];
  description: string;
  featured?: boolean;
  editorsPick?: boolean;
  isNew?: boolean;
  spokes: SpokeSlug[]; // which spoke sections this listing appears in
  // Spoke-specific attributes
  wifiSpeed?: string;       // work-friendly
  hasDesk?: boolean;        // work-friendly
  petFriendly?: boolean;    // pet-friendly
  petPolicy?: string;       // pet-friendly
  rvHookup?: boolean;       // rv-ready
  rvDetails?: string;       // rv-ready
  evCharger?: boolean;      // ev-ready
  evDetails?: string;       // ev-ready
}

// ─────────────────────────────────────────────────────────────
// UNIQUE STAYS (original + expanded)
// ─────────────────────────────────────────────────────────────
export const STAYS: Stay[] = [
  {
    id: 'redwood-treehouse-ca',
    title: 'Enchanted Redwood Treehouse',
    subtitle: 'Nestled among ancient giants',
    location: 'Guerneville, California',
    state: 'California',
    region: 'West',
    category: 'Treehouses',
    platform: 'Airbnb',
    affiliateUrl: 'https://www.airbnb.com/s/treehouses--California',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/86702083/ByQr52J2uJxPcTScSSaduY/hero-treehouse-JWbjZXvAKxUiXAg4QS7BnL.webp',
    price: 285,
    priceUnit: 'night',
    rating: 4.97,
    reviewCount: 312,
    sleeps: 4,
    bedrooms: 2,
    tags: ['Hot Tub', 'Forest Views', 'Fairy Lights', 'Deck'],
    description: 'Wake up 40 feet above the forest floor in this stunning treehouse perched among century-old redwoods. String lights, a wraparound deck, and floor-to-ceiling windows make this the most magical stay in Northern California.',
    featured: true,
    editorsPick: true,
    spokes: ['unique', 'pet-friendly'],
    petFriendly: true,
    petPolicy: 'Dogs welcome (up to 2, under 50 lbs)',
  },
  {
    id: 'desert-dome-ut',
    title: 'Stargazer Geodesic Dome',
    subtitle: 'Sleep under a billion stars',
    location: 'Moab, Utah',
    state: 'Utah',
    region: 'Southwest',
    category: 'Geodesic Domes',
    platform: 'Airbnb',
    affiliateUrl: 'https://www.airbnb.com/s/glamping--Utah',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/86702083/ByQr52J2uJxPcTScSSaduY/hero-dome-fNq53JMSCre9pYDm759BF5.webp',
    price: 340,
    priceUnit: 'night',
    rating: 4.95,
    reviewCount: 198,
    sleeps: 2,
    bedrooms: 1,
    tags: ['Stargazing', 'Fire Pit', 'Desert Views', 'Telescope'],
    description: 'A transparent geodesic dome set against Utah\'s otherworldly red rock formations. The king bed faces the sky so you can watch the Milky Way from your pillow. Includes a private fire pit and telescope.',
    featured: true,
    editorsPick: true,
    spokes: ['unique'],
  },
  {
    id: 'tugboat-houseboat-me',
    title: 'The Autumn Breeze Tugboat',
    subtitle: 'A floating New England escape',
    location: 'Sebago Lake, Maine',
    state: 'Maine',
    region: 'Northeast',
    category: 'Houseboats',
    platform: 'VRBO',
    affiliateUrl: 'https://www.vrbo.com/search/keywords:houseboat-maine',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/86702083/ByQr52J2uJxPcTScSSaduY/hero-houseboat-6e6D3bBeEjwZSSmSxByNAZ.webp',
    price: 420,
    priceUnit: 'night',
    rating: 4.93,
    reviewCount: 87,
    sleeps: 4,
    bedrooms: 2,
    tags: ['Waterfront', 'Kayaks Included', 'Autumn Foliage', 'Dock'],
    description: 'A lovingly restored 1920s tugboat transformed into a cozy floating home. Porthole windows, original hardwood, and a private dock with kayaks. Best experienced during peak fall foliage season.',
    featured: true,
    editorsPick: false,
    spokes: ['unique', 'pet-friendly'],
    petFriendly: true,
    petPolicy: 'Dogs welcome, life jackets provided for pets',
  },
  {
    id: 'lighthouse-maine',
    title: 'Keeper\'s Watch Lighthouse',
    subtitle: 'Your own private beacon',
    location: 'Pemaquid Point, Maine',
    state: 'Maine',
    region: 'Northeast',
    category: 'Lighthouses',
    platform: 'Airbnb',
    affiliateUrl: 'https://www.airbnb.com/s/lighthouse--Maine',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/86702083/ByQr52J2uJxPcTScSSaduY/stay-lighthouse-nHqEjjahnK5Rot6MrdavF2.webp',
    price: 495,
    priceUnit: 'night',
    rating: 4.98,
    reviewCount: 64,
    sleeps: 6,
    bedrooms: 3,
    tags: ['Ocean Views', 'Rocky Coast', 'Historic', 'Spiral Staircase'],
    description: 'A fully restored 19th-century lighthouse keeper\'s dwelling on the rugged Maine coast. Climb the spiral staircase to the lantern room for 360° ocean views. Lobster boats pass by at dawn.',
    featured: false,
    editorsPick: true,
    spokes: ['unique', 'work-friendly'],
    wifiSpeed: '150 Mbps',
    hasDesk: true,
  },
  {
    id: 'barn-tennessee',
    title: 'The Golden Hour Barn',
    subtitle: 'Rustic luxury in the hills',
    location: 'Leiper\'s Fork, Tennessee',
    state: 'Tennessee',
    region: 'South',
    category: 'Converted Barns',
    platform: 'VRBO',
    affiliateUrl: 'https://www.vrbo.com/search/keywords:barn-tennessee',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/86702083/ByQr52J2uJxPcTScSSaduY/stay-barn-JvwT2jj9bCD3f5FXSDQu76.webp',
    price: 375,
    priceUnit: 'night',
    rating: 4.91,
    reviewCount: 143,
    sleeps: 8,
    bedrooms: 4,
    tags: ['Fire Pit', 'String Lights', 'Rolling Hills', 'Farm Animals'],
    description: 'An 1890s tobacco barn transformed into a stunning event-worthy retreat. Original timber beams, a wildflower meadow, and a stone fire pit with Adirondack chairs. Nashville is just 45 minutes away.',
    featured: false,
    editorsPick: false,
    spokes: ['unique', 'pet-friendly'],
    petFriendly: true,
    petPolicy: 'All pets welcome on the farm — dogs, cats, even horses',
  },
  {
    id: 'cave-sedona-az',
    title: 'The Sandstone Sanctuary',
    subtitle: 'A cave carved by time',
    location: 'Sedona, Arizona',
    state: 'Arizona',
    region: 'Southwest',
    category: 'Cave Dwellings',
    platform: 'Airbnb',
    affiliateUrl: 'https://www.airbnb.com/s/cave--Arizona',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/86702083/ByQr52J2uJxPcTScSSaduY/stay-cave-DzUjvuyWRjdY2ijdYdCnYC.webp',
    price: 520,
    priceUnit: 'night',
    rating: 4.99,
    reviewCount: 41,
    sleeps: 2,
    bedrooms: 1,
    tags: ['Red Rocks', 'Vortex Energy', 'Round Door', 'Desert Garden'],
    description: 'Carved directly into Sedona\'s iconic red sandstone cliffs, this extraordinary cave dwelling features a round hobbit door, ancient adobe walls, and unobstructed views of Cathedral Rock. Truly one of a kind.',
    featured: false,
    editorsPick: true,
    isNew: true,
    spokes: ['unique'],
  },
  {
    id: 'aframe-colorado',
    title: 'Summit A-Frame Retreat',
    subtitle: 'High altitude, high style',
    location: 'Breckenridge, Colorado',
    state: 'Colorado',
    region: 'West',
    category: 'A-Frame Cabins',
    platform: 'Wander',
    affiliateUrl: 'https://www.wander.com',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/86702083/ByQr52J2uJxPcTScSSaduY/stay-cabin-AmUuWeL8kRptWi2GUxLZh5.webp',
    price: 450,
    priceUnit: 'night',
    rating: 4.96,
    reviewCount: 229,
    sleeps: 6,
    bedrooms: 3,
    tags: ['Hot Tub', 'Ski-In/Ski-Out', 'Mountain Views', 'Fireplace'],
    description: 'A picture-perfect A-frame cabin at 10,000 feet with ski-in/ski-out access, a steaming outdoor hot tub, and floor-to-ceiling windows framing the Rockies. The wood-burning fireplace is the stuff of dreams.',
    featured: false,
    editorsPick: false,
    isNew: true,
    spokes: ['unique', 'work-friendly', 'ev-ready'],
    wifiSpeed: '500 Mbps',
    hasDesk: true,
    evCharger: true,
    evDetails: 'Tesla Wall Connector + J1772 Level 2 (40A)',
  },
  {
    id: 'dome-smoky-mountains-tn',
    title: 'Smoky Mountain Bubble Dome',
    subtitle: 'Where forest meets the cosmos',
    location: 'Gatlinburg, Tennessee',
    state: 'Tennessee',
    region: 'Southeast',
    category: 'Geodesic Domes',
    platform: 'Airbnb',
    affiliateUrl: 'https://www.airbnb.com/s/dome--Tennessee',
    image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800&q=80',
    price: 265,
    priceUnit: 'night',
    rating: 4.89,
    reviewCount: 176,
    sleeps: 2,
    bedrooms: 1,
    tags: ['Forest Views', 'Hot Tub', 'Stargazing', 'Secluded'],
    description: 'A transparent glamping dome nestled in the Smoky Mountains forest. Watch deer wander past your bed at dawn, then soak in the private hot tub under a canopy of fireflies at dusk.',
    featured: false,
    editorsPick: false,
    spokes: ['unique', 'pet-friendly'],
    petFriendly: true,
    petPolicy: 'Dogs welcome (under 30 lbs)',
  },
  {
    id: 'treehouse-oregon',
    title: 'Pacific Canopy Treehouse',
    subtitle: 'Among the Douglas firs',
    location: 'Hood River, Oregon',
    state: 'Oregon',
    region: 'West',
    category: 'Treehouses',
    platform: 'Airbnb',
    affiliateUrl: 'https://www.airbnb.com/s/treehouses--Oregon',
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
    price: 310,
    priceUnit: 'night',
    rating: 4.94,
    reviewCount: 258,
    sleeps: 3,
    bedrooms: 1,
    tags: ['Columbia River Gorge', 'Hiking', 'Waterfall Views', 'Deck'],
    description: 'Perched 35 feet up in old-growth Douglas firs with views of the Columbia River Gorge. A rope bridge connects the sleeping loft to the main deck. Multnomah Falls is a 20-minute drive.',
    featured: false,
    editorsPick: false,
    isNew: true,
    spokes: ['unique'],
  },
  {
    id: 'tiny-home-texas',
    title: 'The Lone Star Tiny House',
    subtitle: 'Big Texas sky, tiny footprint',
    location: 'Wimberley, Texas',
    state: 'Texas',
    region: 'South',
    category: 'Tiny Homes',
    platform: 'VRBO',
    affiliateUrl: 'https://www.vrbo.com/search/keywords:tiny-house-texas',
    image: 'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800&q=80',
    price: 195,
    priceUnit: 'night',
    rating: 4.88,
    reviewCount: 334,
    sleeps: 2,
    bedrooms: 1,
    tags: ['Hill Country', 'Creek Access', 'Hammock', 'Stargazing'],
    description: 'A beautifully crafted 300 sq ft tiny home on a working Hill Country ranch. Swim in the crystal-clear Blanco River, stargaze from the hammock, and wake to the sound of roosters.',
    featured: false,
    editorsPick: false,
    spokes: ['unique', 'rv-ready'],
    rvHookup: true,
    rvDetails: '30-amp hookup, water & sewer, adjacent to main property',
  },
  {
    id: 'glamping-montana',
    title: 'Glacier Safari Tent',
    subtitle: 'Luxury at the edge of wilderness',
    location: 'Whitefish, Montana',
    state: 'Montana',
    region: 'West',
    category: 'Glamping',
    platform: 'Wander',
    affiliateUrl: 'https://www.wander.com',
    image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&q=80',
    price: 385,
    priceUnit: 'night',
    rating: 4.92,
    reviewCount: 112,
    sleeps: 4,
    bedrooms: 2,
    tags: ['Glacier Views', 'Wildlife', 'Wood Stove', 'Guided Hikes'],
    description: 'A luxury canvas safari tent on the edge of Glacier National Park. Grizzly bears roam the meadow at dusk. Includes a wood-burning stove, Persian rugs, and a private chef option.',
    featured: false,
    editorsPick: true,
    spokes: ['unique', 'pet-friendly', 'rv-ready'],
    petFriendly: true,
    petPolicy: 'Dogs welcome — they love the trails',
    rvHookup: true,
    rvDetails: 'Full hookup (50-amp, water, sewer) on adjacent property',
  },
  {
    id: 'castle-hudson-valley',
    title: 'The Hudson Valley Castle',
    subtitle: 'Your kingdom awaits',
    location: 'Rhinebeck, New York',
    state: 'New York',
    region: 'Northeast',
    category: 'Castles & Estates',
    platform: 'Airbnb',
    affiliateUrl: 'https://www.airbnb.com/s/castle--New-York',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
    price: 1200,
    priceUnit: 'night',
    rating: 4.97,
    reviewCount: 53,
    sleeps: 12,
    bedrooms: 6,
    tags: ['Historic', 'Wine Cellar', 'Gardens', 'Hudson River Views'],
    description: 'A genuine 19th-century stone castle on 40 acres in the Hudson Valley. Six bedrooms, a medieval great hall, wine cellar, and formal gardens. The most dramatic backdrop for a family reunion or milestone celebration.',
    featured: false,
    editorsPick: false,
    spokes: ['unique', 'work-friendly', 'ev-ready'],
    wifiSpeed: '1 Gbps fiber',
    hasDesk: true,
    evCharger: true,
    evDetails: 'Two Level 2 chargers in the carriage house (J1772)',
  },

  // ─── WORK-FRIENDLY EXCLUSIVE LISTINGS ─────────────────────
  {
    id: 'nomad-cabin-asheville',
    title: 'The Remote Worker\'s Ridge Cabin',
    subtitle: 'Fiber internet, mountain air',
    location: 'Asheville, North Carolina',
    state: 'North Carolina',
    region: 'Southeast',
    category: 'A-Frame Cabins',
    platform: 'Airbnb',
    affiliateUrl: 'https://www.airbnb.com/s/work-friendly--North-Carolina',
    image: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800&q=80',
    price: 220,
    priceUnit: 'night',
    rating: 4.96,
    reviewCount: 287,
    sleeps: 4,
    bedrooms: 2,
    tags: ['Fiber WiFi', 'Standing Desk', 'Mountain Views', 'Quiet'],
    description: 'Built specifically for remote workers: gigabit fiber, a dedicated office nook with a standing desk, ergonomic chair, and dual monitor setup. The Blue Ridge Parkway is 10 minutes away for your lunch break hike.',
    featured: true,
    editorsPick: true,
    isNew: true,
    spokes: ['work-friendly'],
    wifiSpeed: '940 Mbps fiber',
    hasDesk: true,
  },
  {
    id: 'workfriendly-houseboat-seattle',
    title: 'Lake Union Floating Office',
    subtitle: 'Work with a view of the Space Needle',
    location: 'Seattle, Washington',
    state: 'Washington',
    region: 'West',
    category: 'Houseboats',
    platform: 'VRBO',
    affiliateUrl: 'https://www.vrbo.com/search/keywords:houseboat-seattle',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
    price: 390,
    priceUnit: 'night',
    rating: 4.94,
    reviewCount: 119,
    sleeps: 3,
    bedrooms: 2,
    tags: ['Gigabit WiFi', 'Dedicated Desk', 'Water Views', 'Kayaks'],
    description: 'A stunning houseboat on Lake Union with a dedicated home office, gigabit fiber, and a rooftop deck overlooking the Seattle skyline. Kayaks included for your after-work decompression.',
    featured: false,
    editorsPick: true,
    spokes: ['work-friendly', 'unique'],
    wifiSpeed: '1 Gbps',
    hasDesk: true,
  },
  {
    id: 'workfriendly-dome-joshua-tree',
    title: 'Joshua Tree Desert Office Dome',
    subtitle: 'Deep focus in the high desert',
    location: 'Joshua Tree, California',
    state: 'California',
    region: 'Southwest',
    category: 'Geodesic Domes',
    platform: 'Airbnb',
    affiliateUrl: 'https://www.airbnb.com/s/work-friendly--California',
    image: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&q=80',
    price: 295,
    priceUnit: 'night',
    rating: 4.91,
    reviewCount: 203,
    sleeps: 2,
    bedrooms: 1,
    tags: ['Starlink WiFi', 'Sit-Stand Desk', 'No Distractions', 'Meditation Space'],
    description: 'Starlink satellite internet (200+ Mbps) in the middle of the Mojave. A minimalist dome with a dedicated work zone, noise-canceling headphone set, and a meditation deck for deep focus breaks.',
    featured: true,
    editorsPick: false,
    spokes: ['work-friendly', 'unique'],
    wifiSpeed: '200 Mbps Starlink',
    hasDesk: true,
  },
  {
    id: 'workfriendly-farmhouse-vermont',
    title: 'Green Mountain Digital Farmhouse',
    subtitle: 'Productive in the pastoral',
    location: 'Stowe, Vermont',
    state: 'Vermont',
    region: 'Northeast',
    category: 'Converted Barns',
    platform: 'VRBO',
    affiliateUrl: 'https://www.vrbo.com/search/keywords:work-friendly-vermont',
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
    price: 310,
    priceUnit: 'night',
    rating: 4.89,
    reviewCount: 156,
    sleeps: 6,
    bedrooms: 3,
    tags: ['500 Mbps WiFi', 'Conference Table', 'Printer', 'Ski Access'],
    description: 'A converted Vermont farmhouse with a dedicated conference room, high-speed fiber, and a printer/scanner setup. Perfect for team retreats — ski Stowe in the morning, close deals in the afternoon.',
    featured: false,
    editorsPick: false,
    spokes: ['work-friendly', 'pet-friendly'],
    wifiSpeed: '500 Mbps',
    hasDesk: true,
    petFriendly: true,
    petPolicy: 'Dogs welcome (2 max)',
  },

  // ─── PET-FRIENDLY EXCLUSIVE LISTINGS ──────────────────────
  {
    id: 'petfriendly-ranch-texas',
    title: 'Paws & Pastures Ranch',
    subtitle: 'Where dogs run free',
    location: 'Fredericksburg, Texas',
    state: 'Texas',
    region: 'South',
    category: 'Glamping',
    platform: 'Airbnb',
    affiliateUrl: 'https://www.airbnb.com/s/pet-friendly--Texas',
    image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&q=80',
    price: 245,
    priceUnit: 'night',
    rating: 4.97,
    reviewCount: 421,
    sleeps: 4,
    bedrooms: 2,
    tags: ['Fenced Acre', 'Dog Wash Station', 'Pet Beds Provided', 'Trails'],
    description: 'A Hill Country ranch glamping suite with a fully fenced private acre — your dogs can roam off-leash all day. Dog wash station, pet beds, food bowls, and a welcome treat basket included.',
    featured: true,
    editorsPick: true,
    spokes: ['pet-friendly'],
    petFriendly: true,
    petPolicy: 'All dogs welcome (no size limit), cats welcome too',
  },
  {
    id: 'petfriendly-beachhouse-oregon',
    title: 'Cannon Beach Dog Cottage',
    subtitle: 'Paws on the Pacific',
    location: 'Cannon Beach, Oregon',
    state: 'Oregon',
    region: 'West',
    category: 'Tiny Homes',
    platform: 'VRBO',
    affiliateUrl: 'https://www.vrbo.com/search/keywords:pet-friendly-cannon-beach',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    price: 285,
    priceUnit: 'night',
    rating: 4.93,
    reviewCount: 267,
    sleeps: 4,
    bedrooms: 2,
    tags: ['Dog-Friendly Beach', 'Fenced Yard', 'Dog Wash', 'Haystack Rock Views'],
    description: 'Steps from one of Oregon\'s most dog-friendly beaches, this cozy cottage has a fenced yard, outdoor dog shower, and a basket of dog toys. Haystack Rock is visible from the living room window.',
    featured: false,
    editorsPick: true,
    spokes: ['pet-friendly'],
    petFriendly: true,
    petPolicy: 'Dogs welcome (up to 3), no size restrictions',
  },
  {
    id: 'petfriendly-cabin-smokies',
    title: 'Smoky Mountain Dog Cabin',
    subtitle: 'Tails wagging in Tennessee',
    location: 'Pigeon Forge, Tennessee',
    state: 'Tennessee',
    region: 'Southeast',
    category: 'A-Frame Cabins',
    platform: 'Airbnb',
    affiliateUrl: 'https://www.airbnb.com/s/pet-friendly--Tennessee',
    image: 'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=800&q=80',
    price: 195,
    priceUnit: 'night',
    rating: 4.88,
    reviewCount: 389,
    sleeps: 6,
    bedrooms: 3,
    tags: ['Hot Tub', 'Fenced Yard', 'Dog Trails', 'Mountain Views'],
    description: 'A pet-paradise cabin in the Smokies with a fully fenced half-acre yard, a hot tub, and direct access to dog-friendly hiking trails. Bring the whole pack — up to 3 dogs welcome, no size limit.',
    featured: false,
    editorsPick: false,
    spokes: ['pet-friendly'],
    petFriendly: true,
    petPolicy: 'Up to 3 dogs, any size. Cats welcome.',
  },

  // ─── RV-READY EXCLUSIVE LISTINGS ──────────────────────────
  {
    id: 'rv-ranch-arizona',
    title: 'Sonoran Desert RV Ranch',
    subtitle: 'Full hookups under saguaro skies',
    location: 'Tucson, Arizona',
    state: 'Arizona',
    region: 'Southwest',
    category: 'Glamping',
    platform: 'Direct',
    affiliateUrl: 'https://www.hipcamp.com',
    image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80',
    price: 85,
    priceUnit: 'night',
    rating: 4.92,
    reviewCount: 178,
    sleeps: 6,
    bedrooms: 1,
    tags: ['50-Amp Hookup', 'Water & Sewer', 'Saguaro Views', 'Fire Ring'],
    description: 'A private 5-acre desert ranch with full RV hookups (50-amp, water, sewer), surrounded by giant saguaro cacti. Campfire rings, a shared outdoor kitchen, and the darkest skies in the Southwest.',
    featured: true,
    editorsPick: true,
    spokes: ['rv-ready'],
    rvHookup: true,
    rvDetails: '50-amp full hookup (water, sewer, electric). Up to 45ft rigs.',
  },
  {
    id: 'rv-farm-vermont',
    title: 'Green Acres RV Farm Stay',
    subtitle: 'Park among the apple orchards',
    location: 'Woodstock, Vermont',
    state: 'Vermont',
    region: 'Northeast',
    category: 'Glamping',
    platform: 'Direct',
    affiliateUrl: 'https://www.hipcamp.com',
    image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&q=80',
    price: 75,
    priceUnit: 'night',
    rating: 4.90,
    reviewCount: 94,
    sleeps: 4,
    bedrooms: 1,
    tags: ['30-Amp Hookup', 'Apple Orchard', 'Farm Animals', 'Fall Foliage'],
    description: 'Park your rig in a working Vermont apple orchard with 30-amp hookups and a water connection. Pick apples, meet the goats, and watch the fall foliage from your awning. Pure New England magic.',
    featured: false,
    editorsPick: false,
    spokes: ['rv-ready', 'pet-friendly'],
    rvHookup: true,
    rvDetails: '30-amp hookup, water only (no sewer — dump station 2 miles)',
    petFriendly: true,
    petPolicy: 'Dogs welcome on leash around farm animals',
  },
  {
    id: 'rv-coast-california',
    title: 'Big Sur Coastal RV Spot',
    subtitle: 'Park at the edge of the Pacific',
    location: 'Big Sur, California',
    state: 'California',
    region: 'West',
    category: 'Glamping',
    platform: 'Direct',
    affiliateUrl: 'https://www.reservecalifornia.com',
    image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80',
    price: 120,
    priceUnit: 'night',
    rating: 4.95,
    reviewCount: 312,
    sleeps: 6,
    bedrooms: 1,
    tags: ['Ocean Views', '50-Amp', 'Whale Watching', 'Cliffside'],
    description: 'One of the most coveted RV spots on the Pacific Coast — a cliffside site overlooking the Big Sur coastline. Full hookups, whale watching from your site, and the most dramatic sunsets in California.',
    featured: false,
    editorsPick: true,
    spokes: ['rv-ready'],
    rvHookup: true,
    rvDetails: '50-amp full hookup, water & sewer. Max length 35ft.',
  },
  {
    id: 'rv-mountains-colorado',
    title: 'Rocky Mountain High RV Park',
    subtitle: 'Altitude and attitude',
    location: 'Estes Park, Colorado',
    state: 'Colorado',
    region: 'West',
    category: 'Glamping',
    platform: 'Direct',
    affiliateUrl: 'https://www.reserveamerica.com',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
    price: 95,
    priceUnit: 'night',
    rating: 4.88,
    reviewCount: 445,
    sleeps: 8,
    bedrooms: 1,
    tags: ['Rocky Mountain NP', '50-Amp', 'Elk Meadow', 'Hiking Access'],
    description: 'Gateway to Rocky Mountain National Park — full hookup sites with elk grazing past your rig at dawn. Trailheads within walking distance. The most convenient base camp in Colorado.',
    featured: false,
    editorsPick: false,
    spokes: ['rv-ready', 'pet-friendly'],
    rvHookup: true,
    rvDetails: '50-amp full hookup. Pull-through sites up to 60ft.',
    petFriendly: true,
    petPolicy: 'Dogs welcome on leash',
  },

  // ─── EV-READY EXCLUSIVE LISTINGS ──────────────────────────
  {
    id: 'ev-modern-villa-palm-springs',
    title: 'Desert Modern EV Villa',
    subtitle: 'Charge up in mid-century style',
    location: 'Palm Springs, California',
    state: 'California',
    region: 'Southwest',
    category: 'Tiny Homes',
    platform: 'Airbnb',
    affiliateUrl: 'https://www.airbnb.com/s/ev-charger--California',
    image: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&q=80',
    price: 425,
    priceUnit: 'night',
    rating: 4.96,
    reviewCount: 189,
    sleeps: 4,
    bedrooms: 2,
    tags: ['Tesla Charger', 'Pool', 'Mid-Century Modern', 'Mountain Views'],
    description: 'A stunning mid-century modern villa with a Tesla Wall Connector and J1772 Level 2 charger in the private garage. Pool, mountain views, and all the Palm Springs glamour you can handle.',
    featured: true,
    editorsPick: true,
    spokes: ['ev-ready', 'unique'],
    evCharger: true,
    evDetails: 'Tesla Wall Connector (48A) + J1772 Level 2 (40A) in private garage',
  },
  {
    id: 'ev-farmhouse-napa',
    title: 'Napa Valley EV Wine Farmhouse',
    subtitle: 'Charge while you sip',
    location: 'Napa, California',
    state: 'California',
    region: 'West',
    category: 'Converted Barns',
    platform: 'VRBO',
    affiliateUrl: 'https://www.vrbo.com/search/keywords:ev-charger-napa',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    price: 680,
    priceUnit: 'night',
    rating: 4.94,
    reviewCount: 76,
    sleeps: 8,
    bedrooms: 4,
    tags: ['Level 2 Charger', 'Wine Cellar', 'Vineyard Views', 'Outdoor Kitchen'],
    description: 'A converted wine country farmhouse on a working vineyard with two Level 2 EV chargers in the barn. Wake up to vineyard rows, charge your car overnight, and spend the day on the wine trail.',
    featured: false,
    editorsPick: true,
    spokes: ['ev-ready', 'unique'],
    evCharger: true,
    evDetails: 'Two J1772 Level 2 chargers (40A each) in the barn',
  },
  {
    id: 'ev-cabin-asheville',
    title: 'Blue Ridge EV Mountain Cabin',
    subtitle: 'Eco-conscious mountain escape',
    location: 'Asheville, North Carolina',
    state: 'North Carolina',
    region: 'Southeast',
    category: 'A-Frame Cabins',
    platform: 'Airbnb',
    affiliateUrl: 'https://www.airbnb.com/s/ev-charger--North-Carolina',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80',
    price: 285,
    priceUnit: 'night',
    rating: 4.91,
    reviewCount: 134,
    sleeps: 4,
    bedrooms: 2,
    tags: ['Level 2 Charger', 'Solar Powered', 'Hot Tub', 'Eco-Friendly'],
    description: 'A solar-powered mountain cabin with a Level 2 EV charger and a commitment to zero-waste hosting. Hot tub, composting, organic garden, and the cleanest mountain air in the Southeast.',
    featured: false,
    editorsPick: false,
    isNew: true,
    spokes: ['ev-ready', 'work-friendly'],
    evCharger: true,
    evDetails: 'Level 2 J1772 (32A) — solar powered, ~25 miles/hr charge rate',
    wifiSpeed: '300 Mbps',
    hasDesk: true,
  },
  {
    id: 'ev-beach-house-hamptons',
    title: 'Hamptons EV Beach House',
    subtitle: 'Arrive green, leave recharged',
    location: 'East Hampton, New York',
    state: 'New York',
    region: 'Northeast',
    category: 'Castles & Estates',
    platform: 'VRBO',
    affiliateUrl: 'https://www.vrbo.com/search/keywords:ev-charger-hamptons',
    image: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80',
    price: 1450,
    priceUnit: 'night',
    rating: 4.97,
    reviewCount: 38,
    sleeps: 10,
    bedrooms: 5,
    tags: ['Tesla Charger', 'Pool', 'Beachfront', 'Chef\'s Kitchen'],
    description: 'A Hamptons beachfront estate with two Tesla Wall Connectors and a J1772 Level 2 charger in the 3-car garage. Pool, chef\'s kitchen, and direct beach access. The ultimate EV road trip terminus.',
    featured: false,
    editorsPick: true,
    spokes: ['ev-ready'],
    evCharger: true,
    evDetails: 'Two Tesla Wall Connectors (48A) + J1772 Level 2 (40A) in 3-car garage',
  },
];

// ─────────────────────────────────────────────────────────────
// SPOKE METADATA
// ─────────────────────────────────────────────────────────────
export interface SpokeConfig {
  slug: SpokeSlug;
  title: string;
  tagline: string;
  description: string;
  heroEmoji: string;
  accentColor: string;      // OKLCH
  accentColorLight: string; // OKLCH
  heroImage: string;
  stats: { value: string; label: string }[];
  filterLabel: string;
  externalDomain: string;
  seoTitle: string;
  seoDescription: string;
}

export const SPOKES: SpokeConfig[] = [
  {
    slug: 'unique',
    title: 'Unique Stays',
    tagline: 'Sleep somewhere extraordinary.',
    description: 'Treehouses, geodesic domes, lighthouses, cave dwellings, and architectural wonders. The stays that make your jaw drop.',
    heroEmoji: '🌲',
    accentColor: 'oklch(0.55 0.14 38)',
    accentColorLight: 'oklch(0.93 0.025 75)',
    heroImage: 'https://d2xsxph8kpxj0f.cloudfront.net/86702083/ByQr52J2uJxPcTScSSaduY/hero-treehouse-JWbjZXvAKxUiXAg4QS7BnL.webp',
    stats: [
      { value: '400+', label: 'Curated Stays' },
      { value: '48', label: 'States' },
      { value: '10', label: 'Categories' },
    ],
    filterLabel: 'Category',
    externalDomain: 'uniquestaysusa.com',
    seoTitle: 'Unique Stays USA — Treehouses, Domes, Lighthouses & More',
    seoDescription: 'Discover the most extraordinary short-term rentals in America. Curated treehouses, geodesic domes, cave dwellings, lighthouses, and more on Airbnb, VRBO, and Wander.',
  },
  {
    slug: 'work-friendly',
    title: 'Work-Friendly Stays',
    tagline: 'Your office with a view.',
    description: 'WiFi-verified, desk-equipped, distraction-free. The best remote work retreats across America — for solo nomads and team off-sites alike.',
    heroEmoji: '💻',
    accentColor: 'oklch(0.45 0.12 250)',
    accentColorLight: 'oklch(0.93 0.025 250)',
    heroImage: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=1600&q=80',
    stats: [
      { value: '150+', label: 'Verified Stays' },
      { value: '100+', label: 'Mbps Avg WiFi' },
      { value: '38', label: 'States' },
    ],
    filterLabel: 'WiFi Speed',
    externalDomain: 'workfriendlystays.com',
    seoTitle: 'Work-Friendly Stays USA — Remote Work Vacation Rentals',
    seoDescription: 'Find the best remote work vacation rentals in America. WiFi-verified, desk-equipped stays on Airbnb, VRBO, and Wander. Perfect for digital nomads and team retreats.',
  },
  {
    slug: 'pet-friendly',
    title: 'Pet-Friendly Stays',
    tagline: 'The whole family is invited.',
    description: 'Fenced yards, dog wash stations, pet beds, and trails. Stays that genuinely welcome your furry co-pilots — not just tolerate them.',
    heroEmoji: '🐾',
    accentColor: 'oklch(0.50 0.14 145)',
    accentColorLight: 'oklch(0.93 0.025 145)',
    heroImage: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1600&q=80',
    stats: [
      { value: '200+', label: 'Pet-Friendly Stays' },
      { value: '40+', label: 'States' },
      { value: '0', label: 'Size Restrictions*' },
    ],
    filterLabel: 'Pet Type',
    externalDomain: 'stayswithpets.com',
    seoTitle: 'Pet-Friendly Stays USA — Dog & Cat-Friendly Vacation Rentals',
    seoDescription: 'The best pet-friendly vacation rentals in America. Fenced yards, dog wash stations, and trails. Find stays that truly welcome your pets on Airbnb and VRBO.',
  },
  {
    slug: 'rv-ready',
    title: 'RV-Ready Stays',
    tagline: 'Hook up. Kick back. Explore.',
    description: 'Full hookups (30 & 50-amp), pull-through sites, and scenic locations for your rig. From desert ranches to coastal cliffs — the best RV stays in America.',
    heroEmoji: '🚐',
    accentColor: 'oklch(0.50 0.14 60)',
    accentColorLight: 'oklch(0.93 0.025 60)',
    heroImage: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80',
    stats: [
      { value: '120+', label: 'RV Sites' },
      { value: '35', label: 'States' },
      { value: '60ft', label: 'Max Rig Length' },
    ],
    filterLabel: 'Hookup Type',
    externalDomain: 'rvreadystays.com',
    seoTitle: 'RV-Ready Stays USA — Full Hookup RV Sites & Campgrounds',
    seoDescription: 'Find the best RV hookup sites across America. Full hookups (30 & 50-amp), pull-through sites, and scenic locations. From desert ranches to coastal cliffs.',
  },
  {
    slug: 'ev-ready',
    title: 'EV-Ready Stays',
    tagline: 'Charge up. Drive further.',
    description: 'Level 2 chargers, Tesla Wall Connectors, and EV-friendly hosts. The only directory of vacation rentals verified to have on-site EV charging.',
    heroEmoji: '⚡',
    accentColor: 'oklch(0.50 0.14 200)',
    accentColorLight: 'oklch(0.93 0.025 200)',
    heroImage: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=1600&q=80',
    stats: [
      { value: '90+', label: 'EV-Verified Stays' },
      { value: '32', label: 'States' },
      { value: 'L2+', label: 'Charger Level' },
    ],
    filterLabel: 'Charger Type',
    externalDomain: 'evreadystays.com',
    seoTitle: 'EV-Ready Stays USA — Vacation Rentals with EV Charging',
    seoDescription: 'The only curated directory of vacation rentals with on-site EV charging. Level 2, Tesla Wall Connectors, and more. Find EV-friendly Airbnb and VRBO stays.',
  },
];

// ─────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────
export function getStaysBySpoke(slug: SpokeSlug): Stay[] {
  return STAYS.filter((s) => s.spokes.includes(slug));
}

export function getSpokeConfig(slug: SpokeSlug): SpokeConfig | undefined {
  return SPOKES.find((s) => s.slug === slug);
}

export const CATEGORIES: { id: Category; emoji: string; label: string; count: number }[] = [
  { id: 'Treehouses', emoji: '🌲', label: 'Treehouses', count: 48 },
  { id: 'Geodesic Domes', emoji: '🔮', label: 'Geodesic Domes', count: 34 },
  { id: 'Houseboats', emoji: '⛵', label: 'Houseboats', count: 27 },
  { id: 'Lighthouses', emoji: '🏮', label: 'Lighthouses', count: 19 },
  { id: 'Converted Barns', emoji: '🏚️', label: 'Converted Barns', count: 56 },
  { id: 'Cave Dwellings', emoji: '🪨', label: 'Cave Dwellings', count: 12 },
  { id: 'A-Frame Cabins', emoji: '🏔️', label: 'A-Frame Cabins', count: 73 },
  { id: 'Tiny Homes', emoji: '🏡', label: 'Tiny Homes', count: 89 },
  { id: 'Glamping', emoji: '⛺', label: 'Glamping', count: 61 },
  { id: 'Castles & Estates', emoji: '🏰', label: 'Castles & Estates', count: 8 },
];

export const REGIONS = ['All', 'West', 'Southwest', 'South', 'Midwest', 'Northeast', 'Southeast'] as const;
export type Region = typeof REGIONS[number];
